import MyProject.Common.Calculus
import MyProject.Common.LpJensen
import MyProject.Common.Translation
import MyProject.Common.AreaFormula
import MyProject.PDE.Transport
import MyProject.PDE.Laplace
import MyProject.PDE.Heat
import MyProject.PDE.Wave
import MyProject.Sobolev.Basic
import MyProject.Sobolev.Higher
import MyProject.Sobolev.Mollification
import MyProject.Sobolev.Rellich
import MyProject.Sobolev.FrechetKolmogorov
import MyProject.Sobolev.RellichKondrachov
