import MyProject.Calculus
import MyProject.Transport
import MyProject.Laplace
import MyProject.Heat
import MyProject.Wave
import MyProject.Sobolev
import MyProject.LpJensen
import MyProject.Mollification
import MyProject.SobolevHigher
import MyProject.Rellich
import MyProject.FrechetKolmogorov
import MyProject.RellichKondrachov
import MyProject.FrechetKolmogorov
